name: CI Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x, 20.x]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        registry-url: 'https://npm.pkg.github.com/'
        scope: '@RHEcosystemAppEng'
        cache: 'npm'
    - name: Install Dependencies
      run: npm ci
      env:
        # also other environment variable
        NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Invoke LSP entrypoint(server.js)
      run: node dist/server.js
      env:
        # also other environment variable
        NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Run the unit tests
      run: npm test -- --coverage
      env:
        # also other environment variable
        NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}

  build-with-vscode:
    runs-on: ubuntu-latest
    steps:
    - name: pull lsp code
      uses: actions/checkout@v2
    - name: Setup Node env
      uses: actions/setup-node@v3
      with:
        node-version: 18.x
        registry-url: 'https://npm.pkg.github.com/'
        scope: '@RHEcosystemAppEng'
        cache: 'npm'
    - name: Install Dependencies
      run: npm ci
      env:
        # also other environment variable
        NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Create local package tarball
      run: npm pack
      env:
        # also other environment variable
        NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: pull vscode-extension code
      uses: actions/checkout@v2
      with:
        repository: fabric8-analytics/fabric8-analytics-vscode-extension
        path: vscode-extension
    - name: Install vsce
      run: npm i -g vsce
      env:
        # also other environment variable
        NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Install Dependencies
      run: npm ci
      working-directory: ./vscode-extension
      env:
        # also other environment variable
        NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Install local lsp
      run: npm i ../fabric8-analytics-lsp-server-*.tgz
      working-directory: ./vscode-extension
      env:
        # also other environment variable
        NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Remove test files
      run: rm -fr test
      working-directory: ./vscode-extension
    - name: VSCE prepublish
      run: vsce package
      working-directory: ./vscode-extension
    - name: Invoke LSP entrypoint(server.js)
      run: node dist/server.js
      working-directory: ./vscode-extension
    - name: Upload build artifacts
      uses: actions/upload-artifact@v2
      with:
        name: Extension Build - ${{ github.event.pull_request.number }}
        path: ./vscode-extension/*.vsix
